name = "exampledash"
logo = "https://www.pngmart.com/files/11/Rickrolling-PNG-Pic.png"
accent_color = "#dc2626"
service_domain = "example.com"

[services.calibre-web]
name = "librarian"
desc = "read ebooks"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/calibre-web.png"

[services.drawio]
name = "draw"
desc = "create drawings and diagrams"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/draw-io.png"

[services.grocy]
name = "food"
desc = "plan meals and track ingredients"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/grocy.png"

[services.homeassistant]
name = "home"
domain = "internal.example.com"
desc = "control heaters, curtains and lights"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/home-assistant.png"

[services.immich]
name = "photos"
desc = "maintain a photo library"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png"

[services.jellyfin]
name = "flix"
domain = "seedbox.example.com"
desc = "watch movies and tv"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png"

[services.paperless-ngx]
name = "paper"
desc = "archive important documents"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png"
