# blobdash.example.toml
#
# This is an example configuration file for blobdash (https://github.com/thcrt/blobdash).
#
# To get started quickly, copy it to `blobdash.toml`, make edits and bind mount it to your blobdash
# container.

name = "mydash"
logo = "https://raw.githubusercontent.com/thcrt/blobdash/refs/heads/main/src/blobdash/static/blobcat.png"
accent_color = "#dc2626"
service_domain = "example.com"

about = """
<h4>Welcome to my dashboard</h4>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
"""

[dashdot]
enabled = true
host = "https://dash.mauz.dev"
show_values = true
widgets = [
    "cpu",
    "ram",
    "network",
]

[auth]
enabled = true
header = "X-App-User"
logout_url = "#"

# To fetch apps from an authentik instance, modify and uncomment the below options.
# [auth.apps]
# enabled = true
# host = "https://auth.example.com"
# token = "super-secret-token"

# An example of an app being manually added 
[apps.calibre-web]
name = "librarian"
desc = "read ebooks"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/calibre-web.png"
url = "#"

# We can also only set some attributes, overriding apps fetched from the auth provider
[apps.jellyfin]
name = "notflix"
desc = "watch movies and tv"
