# blobdash.example.toml
#
# This is an example configuration file for blobdash (https://github.com/thcrt/blobdash).
#
# To get started quickly, copy it to `blobdash.toml`, make edits and bind mount it to your blobdash
# container.

name = "mydash"
logo = "https://raw.githubusercontent.com/thcrt/blobdash/refs/heads/main/src/blobdash/static/blobcat.png"
accent_color = "#dc2626"
service_domain = "example.com"

about = """
<h4>Welcome to my dashboard</h4>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
"""

[auth]
header = "X-App-User"
logout_url = "#"

[dashdot]
enabled = true
host = "https://dash.mauz.dev"
show_values = true
widgets = [
    "cpu",
    "ram",
    "network",
]

[services.calibre-web]
name = "librarian"
desc = "read ebooks"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/calibre-web.png"
url = "#"

[services.drawio]
name = "draw"
desc = "create drawings and diagrams"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/draw-io.png"
url = "#"

[services.grocy]
name = "food"
desc = "plan meals and track ingredients"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/grocy.png"
url = "#"

[services.homeassistant]
name = "home"
domain = "internal.example.com"
desc = "control heaters, curtains and lights"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/home-assistant.png"
url = "#"

[services.immich]
name = "photos"
desc = "maintain a photo library"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png"
url = "#"

[services.jellyfin]
name = "flix"
domain = "seedbox.example.com"
desc = "watch movies and tv"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png"
url = "#"

[services.paperless-ngx]
name = "paper"
desc = "archive important documents"
icon = "https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png"
url = "#"
